APPLICATION = picotcp
include ../Makefile.tests_common

CFLAGS += -g

USEMODULE += xtimer
USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps
USEMODULE += picotcp_contrib
USEMODULE += picotcp_netdev
USEMODULE += netdev_tap

USEPKG += picotcp

include $(RIOTBASE)/Makefile.include
