APPLICATION = picotcp
include ../Makefile.tests_common

CFLAGS += -g

USEMODULE += xtimer
USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps
USEMODULE += picotcp_contrib
USEMODULE += picotcp_netdev2
USEMODULE += netdev2_tap

USEPKG += picotcp

include $(RIOTBASE)/Makefile.include
