APPLICATION = picotcp
include ../Makefile.tests_common

USEMODULE += xtimer
USEMODULE += shell
USEMODULE += picotcp_contrib
USEMODULE += picotcp_netdev2
USEMODULE += netdev2_tap

USEPKG += picotcp

include $(RIOTBASE)/Makefile.include
