include ../Makefile.tests_common

# include and auto-initialize all available sensors
USEMODULE += saul_default
USEMODULE += saul_gpio

BOARD = olimex-stm32-p405

USEMODULE += xtimer

include $(RIOTBASE)/Makefile.include
