PKG_NAME=picotcp
PKG_URL=https://github.com/tass-belgium/picotcp
PKG_VERSION=f6db6df84ea13544ffde5a0b04be71a6f3c25440

.PHONY: all

all: git-download
	"$(MAKE)" -C $(PKG_BUILDDIR)

include $(RIOTBASE)/pkg/pkg.mk
